Bring-Up New Methods

diff --git a/.github/workflows/mirror-bot.yml b/.github/workflows/mirror-bot.yml
--- a/.github/workflows/mirror-bot.yml
+++ b/.github/workflows/mirror-bot.yml
@@ -1,4 +1,4 @@
-name: PMirror Bot Environment
+name: PriiiiyoMirrorBot Environment
 
 on:
   push:
@@ -10,10 +10,10 @@ env:
   # Change these values if you have forked it for your own works
   GitHubMail: ${{ secrets.GITHUBMAIL }}
   GitHubName: ${{ secrets.GITHUBNAME }}
-  Branch: "master"
 
 jobs:
-  build:
+  # 1st Job for running bot 1
+  bot1:
     runs-on: ubuntu-latest
 
     steps:
@@ -32,20 +32,72 @@ jobs:
 
       - name: Clone The Secret Mirror Repository
         run: |
-          git clone https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.MIRROR_REPOSLUG }} -b ${Branch} source
+          git clone https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.MIRROR_REPOSLUG }} source
+
       - name: Compile The Mirroring Docker Container
         run: |
           cd source || exit 1
           docker container prune --force || true
           docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t mirror-bot
           docker image ls
+
       - name: running Docker
         timeout-minutes: 340
         continue-on-error: true
         run: |
           docker run --privileged --rm -i mirror-bot
-      - name: Loop Workflow
+ 
+  # 2nd Job for running bot 2
+  bot-2:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@main
+
+      - name: Set Git Configs & Secrets
+        run: |
+          git config --global user.email ${GitHubMail}
+          git config --global user.name ${GitHubName}
+          git config --global credential.helper store
+          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
+
+      # Cleanup The Actions Workspace Using Custom Composite Run Actions
+      - uses: rokibhasansagar/slimhub_actions@main
+
+      - name: Clone The Secret Mirror Repository
+        run: |
+          git clone https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.MIRROR_REPOSLUG_2 }} source
+
+      - name: Compile The Mirroring Docker Container
+        run: |
+          cd source || exit 1
+          docker container prune --force || true
+          docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t mirror-bot
+          docker image ls
+
+      - name: running Docker
+        timeout-minutes: 340
         continue-on-error: true
+        run: |
+          docker run --privileged --rm -i mirror-bot
+                 
+  # 3rd Job for looping the workflow after job 1 & 2 completes
+  looper:
+    needs: [bot-1, bot-2]
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@main
+      - name: Set Git Configs & Secrets
+        run: |
+          git config --global user.email ${GitHubMail}
+          git config --global user.name ${GitHubName}
+          git config --global credential.helper store
+          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
+          
+      - name: Loop Workflow
         run: |
           # ${GITHUB_REPOSITORY} is the repo slug which runs this script
           git clone https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
